version: '3.9'
services:
  agritech:
    container_name: agritech
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./:/agritech
    depends_on:
      - db
    
  db:
    image: postgres
    container_name: agritechDB
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agritech
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
